from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('inventories', views.inventories, name='inventories'),
    path('inventories_form', views.inventories_new_report,
         name='inventories_new_report'),
    path('inventories_export', views.inventories_export),
    path('operations_center', views.operations_center, name='operations_center'),
    path('operations_center/<pk>', views.edit_operation_center,
         name='edit_operations_center'),
    path('new_operations_center', views.new_operation_center,
         name='new_operations_center'),
    path('referrals', views.referrals, name='referrals'),
    path('referrals/<pk>', views.edit_referral, name='edit_referral'),
    path('referrals/print/<pk>', views.print_referral, name='print_referral'),
    path('referrals/detail/<pk>', views.detail_referral, name='detail_referral'),
    path('new_referral', views.new_referrals, name='new_referral'),
    
    path('zones', views.zones, name='zones'),
    path('regions', views.regions, name='regions'),
    # recibe el id del departamento
    path('regions/<pk>', views.cities_region, name='cities_region'),
    path('third_party_users', views.third_party_users, name='third_party_users'),
    path('add_third_party_users', views.add_third_party_users,
         name='add_third_party_users'),
    path('third_party_users/<pk>', views.edit_third_party_users,
         name='edit_third_party_users'),
    path('vehicles', views.vehicles, name='vehicles'),
    path('new_vehicle', views.new_vehicle, name='new_vehicle'),
    path('vehicles/<pk>', views.edit_vehicle, name='edit_vehicle'),
    path('shipments', views.shipments, name='shipments'),
    path('shipments/<pk>', views.edit_shipment, name='edit_shipment'),
    path('new_shipment', views.new_shipment, name='new_shipment'),
    path('fertilizers', views.fertilizers, name='fertilizers'),
    path('fertilizers/<int:pk>', views.edit_fertilizer, name='edit_fertilizer'),
    path('new_fertilizer', views.new_fertilizer, name='new_fertilizer'),
    path('fertilizers_export', views.fertilizers_export),
    path('vehicle_lines', views.vehicle_lines, name='vehicle_lines'),
    path('vehicles_capacity', views.vehicles_capacity, name='vehicles_capacity'),
    path('travel_costs', views.travel_costs, name='travel_costs'),
    path('travel_costs/<pk>', views.edit_travel_costs, name='edit_travel_cost'),
    path('new_travel_costs', views.new_travel_costs, name='new_travel_costs'),
    path('companies', views.companies, name='companies'),
    path('dev_referral_export', views.dev_referral_export),
    path('referrals_export', views.referrals_export),
    path('vendors', views.vendors, name='vendors'),
    path('rapipollo', views.rapipollo, name='rapipollo'),
    path('datosperson', views.datosperson, name='datosperson'),




    #     path('profile', views.profile, name='profile'),

    path('api/operations_center', views.operation_center_list),
    path('api/operations_center/<pk>', views.operation_center_detail),
    path('api/inventories', views.inventories_list),
    path('api/referrals', views.referrals_list),
    path('api/referrals/<int:referral_id>/documents/<int:document_id>', views.referral_document_detail),
    path('api/referrals/<int:referral_id>/documents', views.referral_documents),
    path('api/referrals/<int:referral_id>/documents_dev/<int:document_dev_id>', views.referral_document_dev_detail),
    path('api/referrals/<int:referral_id>/documents_dev', views.referral_documents_dev),
    path('api/referrals/<int:referral_id>/siscombas/<int:siscombas_id>', views.referral_siscombas_detail),
    path('api/referrals/<int:referral_id>/siscombas', views.referral_siscombas),
    path('api/referrals/<int:pk>', views.referral_detail),
    path('api/zones', views.zone_list),
    path('api/zones/<pk>', views.zone_detail),
    path('api/regions', views.regions_list),
    path('api/regions/<pk>', views.region_detail),
    path('api/cities', views.cities_list),
    path('api/cities/<pk>', views.city_detail),
    path('api/cities/region/<region_id>', views.cities_region_list),
    path('api/third_party_users', views.third_party_users_list),
    path('api/third_party_users/<pk>', views.third_party_user_detail),
    path('api/vehicles', views.vehicles_list),
    path('api/vehicles/<pk>', views.vehicles_detail),
    path('api/shipments', views.shipments_list),
    path('api/shipments/<pk>', views.shipments_detail),
    path('api/fertilizers', views.fertilizers_list),
    path('api/fertilizers/<int:pk>', views.fertilizer_detail),
    path('api/vehicle_lines', views.vehicle_lines_list),
    path('api/vehicle_lines/<int:pk>', views.vehicle_lines_detail),
    path('api/vehicles_capacity', views.vehicles_capacity_list),
    path('api/vehicles_capacity/<vehicle_id>', views.vehicle_capacity_detail),
    path('api/travel_costs', views.travel_costs_list),
    path('api/travel_costs/<pk>', views.travel_cost_detail),
    path('api/companies', views.companies_list),
    path('api/companies/<int:pk>', views.companies_detail),
    path('api/rapipollos', views.rapipollos_list),
    path('api/sellers', views.seller_list),
    path('api/sellers/<int:pk>', views.seller_detele),
    path('api/rapipollos', views.rapipollos_list),
    path('api/rapipollos/<int:pk>', views.rapipollo_delete),
    path('api/datosperson', views.datosPerson_list),
    path('api/datosperson/<int:pk>', views.datosPerson_delete)


]
