# Generated by Django 4.1 on 2022-10-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('destino', models.CharField(blank=True, max_length=50, null=True)),
                ('kilos_totales', models.CharField(blank=True, max_length=10, null=True)),
                ('costo_flete', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abonos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentrosOperacion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_ciudad', models.CharField(blank=True, max_length=5, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Centros de operación',
                'db_table': 'centros_operacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevRemision',
            fields=[
                ('id_dev_remision', models.BigIntegerField(primary_key=True, serialize=False)),
                ('canastillas', models.BigIntegerField(blank=True, null=True)),
                ('kilos', models.BigIntegerField(blank=True, null=True)),
                ('unidades', models.BigIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dev_remision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocRemision',
            fields=[
                ('numero_doc', models.BigIntegerField(blank=True, null=True)),
                ('kilos', models.FloatField(blank=True, null=True)),
                ('unidades', models.BigIntegerField(blank=True, null=True)),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('canastillas', models.BigIntegerField(blank=True, null=True)),
                ('sellos', models.BigIntegerField(blank=True, null=True)),
                ('id_doc_remision', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doc_remision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('kilos', models.CharField(blank=True, max_length=10, null=True)),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'domicilios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('nit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('predeterminada', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Granjas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre_granja', models.CharField(max_length=100)),
                ('area_cria', models.CharField(max_length=20)),
                ('activo', models.CharField(max_length=20)),
                ('etapa_granja', models.CharField(max_length=20)),
                ('tipo_especies', models.CharField(max_length=20)),
                ('nombre_propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_granja', models.CharField(max_length=20)),
                ('tipo_granjero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'granjas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id_linea', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lineas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rapipollos',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'rapipollos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('id_remision', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_expedicion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('trailer', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('peso_vacio', models.FloatField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_retorno', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_grabo', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siscombas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_tiquete', models.CharField(max_length=20)),
                ('peso_tiquete', models.FloatField()),
            ],
            options={
                'db_table': 'siscombas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('conductor', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'terceros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('id_antiguo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_negocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('registro', models.DateTimeField(blank=True, null=True)),
                ('administrador', models.CharField(blank=True, max_length=2, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('exclusivo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('poliza', models.CharField(blank=True, max_length=20, null=True)),
                ('vencimiento_soat', models.DateTimeField(blank=True, null=True)),
                ('compania_soat', models.CharField(blank=True, max_length=50, null=True)),
                ('linea', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=4, null=True)),
                ('furgon', models.CharField(blank=True, max_length=20, null=True)),
                ('centro_operacion', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapacidadCarga',
            fields=[
                ('placa', models.OneToOneField(db_column='placa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fleet_app.vehiculos')),
                ('peso_vacio', models.FloatField(blank=True, null=True)),
                ('capacidad_carga', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capacidad_carga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostosViaje',
            fields=[
                ('origen', models.OneToOneField(db_column='origen', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fleet_app.ciudades')),
                ('toneladas', models.FloatField(blank=True, null=True)),
                ('combustible', models.FloatField(blank=True, null=True)),
                ('peajes', models.FloatField(blank=True, null=True)),
                ('alimentacion', models.FloatField(blank=True, null=True)),
                ('soat', models.FloatField(blank=True, null=True)),
                ('gasto_operativo', models.FloatField(blank=True, null=True)),
                ('gasto_mantenimiento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'costos_viaje',
                'managed': False,
            },
        ),
    ]
