# Generated by Django 4.1 on 2022-10-24 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_app', '0003_alter_centrosoperacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrosoperacion',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
