# Generated by Django 4.1 on 2023-02-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0004_centrosoperacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_producto',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='centrosoperacion',
            name='codigo_ciudad',
            field=models.ForeignKey(blank=True, db_column='codigo_ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet_app.ciudades'),
        ),
    ]
