# Generated by Django 4.1 on 2023-03-02 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0005_tiposproducto_alter_centrosoperacion_codigo_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipodocumento', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.ForeignKey(blank=True, db_column='cedula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet_app.terceros')),
            ],
        ),
    ]
