# Generated by Django 4.1 on 2023-04-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0006_datosperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='celular',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
