# Generated by Django 4.1 on 2023-04-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0007_alter_datosperson_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
