# Generated by Django 4.1 on 2023-04-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0008_alter_datosperson_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='documento',
            field=models.ForeignKey(blank=True, db_column='cedula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet_app.datosperson'),
        ),
    ]
