# Generated by Django 4.1 on 2023-04-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0009_alter_datosperson_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
